version: '3'
services:
  db:
    container_name: pirova_mysql
    image: mysql:8
    restart: always
    volumes:
      - ../db:/var/lib/mysql/data
    environment:
      POSTGRES_USER: pirova
      POSTGRES_PASSWORD: pirova
      POSTGRES_DB: pirova
    ports:
      - "5432:5432"
