version: '3'
services:
  db:
    container_name: pirova_mysql
    image: mysql:8
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pirova
      MYSQL_DATABASE: pirova
      MYSQL_USER: pirova
      MYSQL_PASSWORD: pirova
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080